osx_image: xcode9.3
language: objective-c
script:
  # - swift test
  - swift package generate-xcodeproj
  - xcodebuild test -scheme Mappable-Package -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)